Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'
AllCops:
  Exclude:
    - 'gemfiles/**/*'